from enum import Enum


class Joy(Enum):
    LEFT_STICK_HORIZONTAL = 'LEFT_STICK_HORIZONTAL'
    LEFT_STICK_VERTICAL = 'LEFT_STICK_VERTICAL'
    RIGHT_STICK_HORIZONTAL = 'RIGHT_STICK_HORIZONTAL'
    RIGHT_STICK_VERTICAL = 'RIGHT_STICK_VERTICAL'
    LEFT_TRIGGER = 'LEFT_TRIGGER'
    RIGHT_TRIGGER = 'RIGHT_TRIGGER'
